POST http://localhost:8080/users
Content-Type: application/json

{
  "login": "login8",
  "password": "password8",
  "email": "email8@email.com",
  "originCountry": "Poland",
  "originCity": "Opoczno"
}

###

POST http://localhost:8080/users/5/trips
Content-Type: application/json

{
  "userId": 1,
  "country": "Canada",
  "city": "Toronto",
  "firstDay": "2020-11-13",
  "lastDay": "2020-11-19"
}
###
